name: nom_custom_workflow

on:
  push:
    branches:
      - master

jobs:

  deploy-hello-world-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Upload files to /public_html/hello_world_site/ on FTP server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ftpinfo.iutmontp.univ-montp2.fr
          port: 22
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          remote_path: /public_html/TP2_Git_Suite/index.php
          sftp_only: true
